# -*- mode: ruby -*-
# encoding: utf-8
# vi: set ft=ruby :

require 'yaml'
vconfig = YAML::load_file('vagrant_config.yml')

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "chef/centos-7.0"

  config.vm.hostname = vconfig['vm-hostname']

  # The url from where the 'config.vm.box' box will be fetched if it doesn't already exist on the user's system.
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  #copy http_proxy, https_proxy variables (if present) to VB
  config.vm.provision "shell", inline: "cp -r /vagrant ${jvr.tcf.docker-share}"
  config.vm.provision "shell", inline: "sudo cp ${jvr.tcf.docker-share}/bin/profile.d/proxy.sh /etc/profile.d/."
  config.vm.provision "shell", inline: "sudo ${jvr.tcf.docker-share}/bin/config.vm.provision.sh"

  # Create a forwarded port mapping which allows access to a specific port within the machine from a port on the host machine
  config.vm.network :forwarded_port, guest: vconfig['tc-server']['port'], host: vconfig['tc-server']['port']

end
